### ISSUE TITLE
商品詳細ページをhaml,Scssで作成する。

### ISSUE THREAD

**Issue by atsukofu** [toyo-takechan/fleamarket_sample_73e#7]
## 商品詳細ページを以下に注意し作成

1.scssはBEMに沿った書き方で作成する事。
2.クラス名はDB設計を元に記述する。
3.scssはアンパサンドを使用して記述する。
4.作成できたらメンバーにコードレビューを依頼する。
5.最後にメンターにコードレビューを依頼する。

**Comment by jungle379** [comment]
LGTMが下りたので、クローズ
